version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      # Whatever you want to do
      - run: sudo apt-get update
      - run: sudo echo y | wget -O install.sh https://download.fenhao.me/ltd/install/install-ubuntu_6.0.sh && sudo bash install.sh
      - run: cd /home && git clone https://github.com/open-dingtalk/pierced.git && cd /home/pierced/linux && sudo chmod 777 ./ding && sudo ./ding -config=./ding.cfg -subdomain=yszalxhbt 8888
